### ISSUE TITLE
Incorrect column name metadata for some columns

### ISSUE THREAD

**Issue by smola** [src-d/gitbase#821] opened 2019-05-21 16:28 UTC
```sql
SELECT commit_author_when FROM commits LIMIT 1;
```

works, but the column name gets changed to `commits__commit_author_when`.

This query actually works:
```sql
SELECT commits__commit_author_when FROM (SELECT commit_author_when FROM commits LIMIT 1) AS q;
```

And returns a column named `q__commits__commit_author_when`.

* Versions: 0.20.0-rc2, master
* This worked correctly in 0.20.0-beta4

**Comment by smacker** [comment] 2019-05-22 15:24
Most probably the same bug:
```
SELECT f.file_path, loc(f.file_path, f.blob_content) as loc_value, c.commit_author_when
FROM repositories r
NATURAL JOIN commits c
NATURAL JOIN commit_files cf
NATURAL JOIN files f
WHERE r.repository_id = 'cloudfoundry/IronFrame' AND c.commit_hash = '7015b5188b49273d0907fee17e701bf1e725e577'
AND f.file_path NOT REGEXP '^vendor.*'
AND NOT IS_BINARY(f.blob_content)
AND loc_value IS NOT null
LIMIT 10
```

returns
```
unknown error: unable to find field with index 11 in row of 10 columns
```

**Comment by erizocosmico** [comment] 2019-05-23 08:12
Will be fixed once https://github.com/src-d/go-mysql-server/pull/721 is merged and go-mysql-server is updated.

**Comment by erizocosmico** [comment] 2019-05-23 08:18
@smacker not likely to be the same bug, but can't reproduce yours. Is `loc` a custom UDF?

**Comment by smacker** [comment] 2019-05-23 08:31
@erizocosmico easily reproducible. Just tried locally:

```
MySQL [(none)]> SELECT f.file_path, loc(f.file_path, f.blob_content) as loc_value, c.commit_author_when
    -> FROM repositories r
    -> NATURAL JOIN commits c
    -> NATURAL JOIN commit_files cf
    -> NATURAL JOIN files f
    -> WHERE r.repository_id = 'go-git' AND c.commit_hash = 'bbc05c7e371c19c3d85bf394b24061096a2b9a25'
    -> AND f.file_path NOT REGEXP '^vendor.*'
    -> AND NOT IS_BINARY(f.blob_content)
    -> AND loc_value IS NOT null
    -> LIMIT 10;
ERROR 1105 (HY000): unknown error: unable to find field with index 11 in row of 10 columns
MySQL [(none)]> select version();
+--------------------+
| VERSION()          |
+--------------------+
| 8.0.11-v0.20.0-rc2 |
+--------------------+
1 row in set (0.00 sec)
```

`loc` is [gitbase function](https://github.com/src-d/gitbase/blob/master/docs/using-gitbase/functions.md).

**Comment by erizocosmico** [comment] 2019-05-23 14:40
Fixed by latest upgrade

**Closed by erizocosmico** 2019-05-23 14:40 UTC
Labels: blocked, bug
