### ISSUE TITLE
Watch directory with repositories for changes

### ISSUE THREAD

**Issue by smacker** [src-d/gitbase#645] opened 2018-12-04 12:13 UTC
1. It would be nice to discover new repositories without restart
2. Now sure how gitbase behaves now if a repository is deleted/changed. Would be cool to handle such cases correctly.

**Comment by ajnavarro** [comment] 2018-12-04 12:16
Actually, this is not possible. If some repository is detached/attached and you have some indexes on them, that indexes will not be correct. See https://github.com/src-d/gitbase/issues/580

**Comment by ajnavarro** [comment] 2018-12-12 14:49
Shall we close this one @smola ?

**Comment by smola** [comment] 2018-12-12 16:05
@ajnavarro Yes, I'd say this is a duplicate of https://github.com/src-d/gitbase/issues/580

**Comment by ajnavarro** [comment] 2018-12-12 16:07
Closing as duplicated then.

**Closed by ajnavarro** 2018-12-12 16:07 UTC
Labels: empathy-sessions
