### ISSUE TITLE
Negation Expression on indexed column not working correctly

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase#415] opened 2018-08-07 11:57 UTC
Executing the following query:

```sql
mysql> select count(*) from commits where commit_author_email='jenkins@review.openstack.org' group by repository_id;
+----------+
| COUNT(*) |
+----------+
|     1213 |
+----------+
1 row in set (0,37 sec)
```
All appears to be good, but if we just want the count of commits that doesn't have that commit author email:

```sql
mysql> select count(*) from commits where commit_author_email!='jenkins@review.openstack.org' group by repository_id;
+----------+
| COUNT(*) |
+----------+
|     6569 |
+----------+
1 row in set (1,00 sec)

```
The result appears to be not correct. The complete count result:
```
DEBU[2114] finished pilosa indexing                      duration=34m42.734502461s id=commits_author_email_idx mapping=30.782425411s pilosa=7.745289374s rows=2567829
```

So I suppose the second query should return 2567829-1213 = 2566616

**Comment by mcarmonaa** [comment] 2018-08-07 12:30
Just in case, if there is more than one repository and that email doesn't appear in all of them the returned value won't be `totalrows-1213`

**Comment by kuba--** [comment] 2018-08-07 12:34
@mcarmonaa thanks - I'll check what I get without any indexes, with pilosa and pilosalib. We'll see how it goes.

**Comment by kuba--** [comment] 2018-08-07 21:05
I cannot reproduce it. I tested on my 3 small repos (~180 rows) and on single gitbase (~580 rows)

**Comment by kuba--** [comment] 2018-08-08 11:53
it may be fixed by https://github.com/src-d/go-mysql-server/pull/325
But I could not reproduce it.

**Comment by kuba--** [comment] 2018-08-08 17:08
@ajnavarro after merging https://github.com/src-d/go-mysql-server/pull/326 and upgrading mysql, please double check if you can reproduce it.

**Comment by kuba--** [comment] 2018-08-10 13:10
In my opinion it should be fixed by already merged fix for NOT operator.

**Comment by kuba--** [comment] 2018-08-14 06:48
After update master, this issue can be closed (I believe).

**Comment by ajnavarro** [comment] 2018-08-14 09:08
I'm gonna test it again with the new RC

**Comment by erizocosmico** [comment] 2018-08-16 10:17
Did it work @ajnavarro?

**Comment by ajnavarro** [comment] 2018-08-16 11:12
@erizocosmico I'm having the same result with the latest version.

**Comment by ajnavarro** [comment] 2018-08-16 11:17
Executing `select commit_author_email from commits where commit_author_email != 'jenkins@review.openstack.org'` without indexes the outputs is way larger.

**Comment by ajnavarro** [comment] 2018-08-16 12:26
I can reproduce the error with siva files downloaded using the following command:

`pga list -l python -f json | head -n 10 | jq -r '.sivaFilenames[]' | pga get -i -o repositories`

**Comment by kuba--** [comment] 2018-08-16 12:34
Ok, thanks, I'll dive deeply into this.

**Comment by kuba--** [comment] 2018-08-16 21:01
It's not related to `NOT`. Regular full scan for siva files return incorrect results (not all of them). But in index (mapping, bitmap) we have everything and return all of them via iterator. 
I'll have to check iterator and decoder for siva files.

**Comment by kuba--** [comment] 2018-08-16 22:41
Decoder looks fine. Moreover for old pilosa index everything should be fine. In my opinion sth. is broken in `pilosalib` driver.

**Comment by kuba--** [comment] 2018-08-17 07:25
I believe this problem appeared only for `pilosalib` driver, where we had a bug and did *not* clean `bitBatch` structure (used for importing fields in `pilosa`).

**Closed** 2018-08-17 08:51 UTC
Labels: bug
