### ISSUE TITLE
Group by can not use indexes

### ISSUE THREAD

**Issue by dpordomingo** [src-d/gitbase#721] opened 2019-03-06 09:47 UTC
discovered at https://github.com/src-d/empathy-sessions/issues/37#issuecomment-470041061
I think it's related or caused by https://github.com/src-d/gitbase/issues/720

If filtering by language without indexes, it takes ~15s
```shell
time srcd sql "SELECT file_path, language(file_path, blob_content)
FROM files
WHERE language(file_path, blob_content)='JSX';"
real	0m12.926s
```

Then I created an index, following your [example to create an index on language expresion](https://docs.sourced.tech/gitbase/using-gitbase/examples#create-an-index-for-an-expression-on-a-table)
```shell
$ srcd sql "CREATE INDEX files_lang_idx ON files USING pilosa (language(file_path, blob_content));
```

And query again, and the time processing was reduded from ~15s to ~.3s what is nice.

Then I query grouping by lang and it takes ~10s because the index is not applyed on aliased cols https://github.com/src-d/gitbase/issues/720.
```shell
$ time srcd sql "SELECT count(*), language(file_path, blob_content) as lang
FROM files
GROUP BY lang;"
+----------+--------------------+
| COUNT(*) |        LANG        |
+----------+--------------------+
|      563 | JSON with Comments |
|     1568 | JSON               |
|      ...                      |
+----------+--------------------+

real	0m10.908s

```

Also tryed grouping by `language` func, but `GROUP BY` does not let you do it
```shell
$ srcd sql "SELECT count(*), language(file_path, blob_content) as lang
FROM files
GROUP BY language(file_path, blob_content);"
2019/03/06 10:20 rpc error: code = Unknown desc = SQL query failed: Error 1105: unknown error:
                 group by aggregation 'language(files.file_path, files.blob_content)' not supported

```

**Comment by erizocosmico** [comment] 2019-03-20 09:38
The last issue you mention should be fixed when we upgrade go-mysql-server.

**Comment by dpordomingo** [comment] 2019-03-20 09:57
and the first one could be also fixed by #720

If you close this issue once the fix has been released, and I'll try both :)

**Comment by erizocosmico** [comment] 2019-04-03 08:13
Regarding your original request with this query:

```sql
SELECT count(*), language(file_path, blob_content) as lang
FROM files
GROUP BY lang
```

Indexes are only used when you specify a condition.

For example, this would use the index:

```sql
SELECT count(*), language(file_path, blob_content) as lang
FROM files
WHERE language(file_path, blob_content) = 'JSX'
GROUP BY lang
```

(the second language could become lang once gitbase is updated)

So this is working as intended. Without any filter, it's a full scan, and indexes are not used in full scans. It does not have anything to do with the group by.

**Closed** 2019-04-03 08:14 UTC
Labels: empathy

**Comment by dpordomingo** [comment] 2019-04-03 11:24
Total newbie on this field, but let me try...

having this index:
```sql
CREATE INDEX commits_idx ON commits USING pilosa (commit_author_name, commit_author_when);
```

Then we query:
```sql
SELECT min(commit_author_when)
  FROM commits
  GROUP BY commit_author_name
```
And considering your explanation:
>_without any filter, it's a full scan, and indexes are not used in full scans_
it will be performed a full scan because `commits_idx` index won't be used.
Did I understood you?

But what I understood is that full scan could be avoided in that situation because of the index.

Same about the ordering.
Having this query:
```sql
SELECT commit_author_name
  FROM commits
  ORDER BY commit_author_name
```
Is it not speeded up by the index?
I think it should rely on index order instead of doing a full scan, and sorting on memory.
Or is it a `pilosa` limitation?

And my major doubt about index use.
Since we can index computed values, and since they can be the result of heavy operations, why not relying on the index if possible?

having this index:
```sql
CREATE INDEX files_lang_idx ON files USING pilosa (language(file_path, blob_content));
```
during the index creation it will be queried `bblfsh` to get the language for every file, ending with something like `lang -> file`;

Then doing something like:
```sql
SELECT count(*), language(file_path, blob_content) as lang
  FROM files
  GROUP BY lang;"
```
could get the results only with the info from index, instead of doing a full scan, and querying again `bblfsh`.

_**More info:**_

Did not read it completely, but I saw there some concepts that align with the ideas I exposed above:
- https://dev.mysql.com/doc/refman/8.0/en/group-by-optimization.html
- https://dev.mysql.com/doc/refman/8.0/en/order-by-optimization.html
- https://www.itprotoday.com/sql-server/indexing-sort-performance

Or maybe it is not aplicable at all because our index can not offer that features.

**Comment by erizocosmico** [comment] 2019-04-03 11:40
Oh, yes, it's a limitation of our current implementation (as in it's not implemented yet, but probably could be). Indexes could perfectly be used for full scans (even though it would probably only be worth it for indexes with expensive expressions already computed), order bys and group bys. It's something we know could be done, but it's not a priority AFAIK.

**Comment by dpordomingo** [comment] 2019-04-03 11:43
So I think this could be considered as a feature request.
If you or @ajnavarro agree I could reopen, or to create a new one somewhere :)
